In [6]:
from pandas import Series, DataFrame
import pandas as pd
import numpy as np

In [7]:
obj = Series([4,-7,-5,3])

In [8]:
obj

0    4
1   -7
2   -5
3    3
dtype: int64

In [9]:
obj.values

array([ 4, -7, -5,  3])

In [10]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [11]:
obj2 = Series([4,7,-5,3], index = ['d','b','a','c'])

In [12]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [13]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [14]:
obj2['a']

-5

In [15]:
obj2[['c','a','d']]

c    3
a   -5
d    4
dtype: int64

In [16]:
obj2[obj2>0]

d    4
b    7
c    3
dtype: int64

In [17]:
'b' in obj2

True

In [18]:
4 in obj2

False

In [19]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [20]:
obj3 = Series(sdata)

In [21]:
obj3

Ohio      35000
Oregon    16000
Texas     71000
Utah       5000
dtype: int64

In [22]:
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj4 = Series(sdata, index = states)
# Utah is gone because it does not appear in the states

In [23]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [24]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [25]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [26]:
obj3+obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [27]:
obj4.name = 'population'

In [28]:
obj4.index.name = 'state'

In [29]:
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [30]:
obj.index = ['Bob','Li','Rech','H']
# have to input the same size of index as the number of the value

In [31]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'], 'year': [2000, 2001, 2002, 2001, 2002],
'pop': [1.5, 1.7, 3.6, 2.4, 2.9]}
frame = DataFrame(data)

In [32]:
frame

pop   state  year
0  1.5    Ohio  2000
1  1.7    Ohio  2001
2  3.6    Ohio  2002
3  2.4  Nevada  2001
4  2.9  Nevada  2002

In [33]:
DataFrame(data, columns=['year','state','pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9

In [34]:
frame2 = DataFrame(data, columns=['year','state','pop'], index=['one','two','three','four','five'])

In [35]:
frame2

year   state  pop
one    2000    Ohio  1.5
two    2001    Ohio  1.7
three  2002    Ohio  3.6
four   2001  Nevada  2.4
five   2002  Nevada  2.9

In [36]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
Name: state, dtype: object

frame2.state

In [37]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
Name: three, dtype: object

In [38]:
frame2['debt'] = 16.5

In [39]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5

In [40]:
frame2['debt'] = np.arange(5.)

In [41]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0

In [42]:
val = Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])
frame2['debt'] = val
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7

In [43]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [44]:
frame3 = DataFrame(pop)
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [45]:
frame3.T

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [46]:
DataFrame(pop, index=[2001, 2002, 2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [47]:
frame3.index.name = 'year'; frame3.columns.name = 'state'

In [48]:
frame3.values

array([[ nan,  1.5],
       [ 2.4,  1.7],
       [ 2.9,  3.6]])

In [49]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7]], dtype=object)

In [50]:
obj = Series(np.arange(3), index=['a', 'b', 'c'])
obj

a    0
b    1
c    2
dtype: int64

In [51]:
index = obj.index
index
# immutable

Index(['a', 'b', 'c'], dtype='object')

In [52]:
index = pd.Index(np.arange(3))
obj2 = Series([1.5, -2.5, 0], index=index)
obj2.index is index

True

In [53]:
obj = Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [54]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [55]:
obj.reindex(['a', 'b', 'c', 'd', 'e'], fill_value=0)

a   -5.3
b    7.2
c    3.6
d    4.5
e    0.0
dtype: float64

In [56]:
obj3 = Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])
obj3

0      blue
2    purple
4    yellow
dtype: object

In [57]:
obj3.reindex(range(6), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [58]:
obj3.reindex(range(6), method='bfill')

0      blue
1    purple
2    purple
3    yellow
4    yellow
5       NaN
dtype: object

In [59]:
frame = DataFrame(np.arange(9).reshape((3,3)),index=['a','c','d'],columns=['Ohio','Texas','California'])
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [60]:
states = ['Texas', 'Utah', 'California']
frame.reindex(columns=states) 
# reindex 的时候，有的column 或者 index 保留原样调换到排好的位置，没有的NaN，原来的schema有但没提到的消失

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [61]:
frame.loc[['a', 'b', 'c', 'd'], states]

Texas  Utah  California
a    1.0   NaN         2.0
b    NaN   NaN         NaN
c    4.0   NaN         5.0
d    7.0   NaN         8.0

obj = Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])

In [62]:
obj = Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [63]:
obj.drop(['a'])

b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [64]:
obj.drop('c')

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [65]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [66]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [67]:
frame.drop(['a','c'])

Ohio  Texas  California
d     6      7           8

In [68]:
frame.drop(['Ohio',"Texas"], axis = 1 )

California
a           2
c           5
d           8

In [69]:
frame < 5

Ohio  Texas  California
a   True   True        True
c   True   True       False
d  False  False       False

In [70]:
obj = Series(range(4), index=['d', 'a', 'b', 'c'])
obj

d    0
a    1
b    2
c    3
dtype: int64

In [71]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [72]:
frame.sort_index(axis=1)

California  Ohio  Texas
a           2     0      1
c           5     3      4
d           8     6      7

In [73]:
frame.sort_index(axis=1, ascending=False)

Texas  Ohio  California
a      1     0           2
c      4     3           5
d      7     6           8

In [82]:
#projection
frame.loc[:,['California']]

California
a       False
c        True
d        True

In [83]:
#filter
frame[frame.California>3]

Ohio  Texas  California
c     3      4           5
d     6      7           8

In [84]:
# filter2
frame.query('Ohio < Texas')

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [ ]:
# aggregate